version: "3.10"

services:
  web:
    
    build: .
    container_name: fastapi_app_pet
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env 
    environment:
      DATABASE_URL: postgresql://postgres:secret@postgres:5432/prueba
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres_sql_pet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: prueba
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: